spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    org.springframework: INFO
app:
  booking:
    min-people: 2
    max-people: 20
  maintenance:
    timings:
      - startTime: "09:00"
        endTime: "09:15"
      - startTime: "13:00"
        endTime: "13:15"
      - startTime: "17:00"
        endTime: "17:15"