CREATE TABLE ROOM (
    ROOM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(14),
    CAPACITY INT
);

CREATE TABLE BOOKING (
    BOOKING_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROOM_ID BIGINT,
    BOOKING_REFERENCE VARCHAR(30),
    MEETING_DATE DATE,
    START_TIME TIME,
    END_TIME TIME,
    NUMBER_OF_PEOPLE INT,
    FOREIGN KEY (ROOM_ID) REFERENCES ROOM (ROOM_ID)
);

INSERT INTO ROOM (NAME, CAPACITY) VALUES ('Amaze', 3);
INSERT INTO ROOM (NAME, CAPACITY) VALUES ('Beauty', 7);
INSERT INTO ROOM (NAME, CAPACITY) VALUES ('Inspire', 12);
INSERT INTO ROOM (NAME, CAPACITY) VALUES ('Strive', 20);
INSERT INTO BOOKING (ROOM_ID, BOOKING_REFERENCE, MEETING_DATE, START_TIME, END_TIME, NUMBER_OF_PEOPLE) VALUES (3, 'BR-001', CURRENT_DATE, '10:00', '11:00', 5);