CREATE TABLE ROOM (
    ROOMID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(14),
    CAPACITY INT
);

CREATE TABLE BOOKING (
    BOOKINGID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROOMID BIGINT,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    NUMBER_OF_PEOPLE INT,
    FOREIGN KEY (ROOMID) REFERENCES ROOM (ROOMID)
);

INSERT INTO ROOM (NAME, CAPACITY) VALUES ('Amaze', 3);
INSERT INTO ROOM (NAME, CAPACITY) VALUES ('Beauty', 7);
INSERT INTO ROOM (NAME, CAPACITY) VALUES ('Inspire', 12);
INSERT INTO ROOM (NAME, CAPACITY) VALUES ('Strive', 20);
INSERT INTO BOOKING (ROOMID, START_TIME, END_TIME, NUMBER_OF_PEOPLE) VALUES (3, CURRENT_DATE || 'T10:00:00', CURRENT_DATE || 'T11:00:00', 5);